sudo: false
language: java
jdk:
- oraclejdk8
install: "./gradlew assemble"
before_script:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=3.4.16 mongodb-org-server=3.4.16 mongodb-org-shell=3.4.16 mongodb-org-mongos=3.4.16 mongodb-org-tools=3.4.16
  - sleep 15 #mongo may not be responded directly. See http://docs.travis-ci.com/user/database-setup/#MongoDB
  - mongo --version
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  apt: true
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- openssl aes-256-cbc -K $encrypted_70c68bed8077_key -iv $encrypted_70c68bed8077_iv
  -in gradle.properties.enc -out gradle.properties -d
after_success:
  - test $TRAVIS_BRANCH = "dev" && ./gradlew uploadArchives
group: "stable"
os: "linux"
